name: MADEK/madek/api-v2
windows:
  2:
    name: app
    command: |
      ./bin/clj-run 2>&1 | tee -a log/debug.log
  5:
    name: psql
    command: |
      psql -d madek
  6:
    name: db
    command: |
      cd datalayer
  7:
    name: test
    command: |
      bundle
